alias a="docker compose exec app $@"
alias d="docker compose exec db $@"
alias p="docker compose exec --user app app php bin/console $@"
alias c="docker compose exec --user app app composer $@"
alias u="docker compose exec --user app -e APP_ENV=test app bin/phpunit $@"
alias openapi="docker compose exec --user app app php bin/console nelmio:apidoc:dump --format=yaml > public/docs/openapi.yaml"
