version: '2'

services:
  web:
    hostname: app-web
    image: nginx:latest
    env_file:
      - .env
    volumes:
      - ./docker/web/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/code
    depends_on:
      - app
    networks:
      mynet:
        ipv4_address: ${IP_SUBNET}.101

  db:
    hostname: app-db
    env_file:
      - .env
    build: ./docker/db
    image: tanasecosminromeo/percona:8.0.29-21-centos
    volumes:
        - db_data:/var/lib/mysql
    networks:
      mynet:
        ipv4_address: ${IP_SUBNET}.103

  app:
    hostname: app-app
    env_file:
      - .env
    depends_on:
      - db
    image: tanasecosminromeo/mailserver:8.1.12RC1-base
    build:
      context: ./docker/php
    privileged: true
    volumes:
      - "./:/code"
    links:
      - db
    restart: always
    networks:
      mynet:
        ipv4_address: ${IP_SUBNET}.104

volumes:
    db_data:

networks:
  mynet:
    driver: bridge
    ipam:
      config:
      - subnet: ${IP_SUBNET}.0/24

